export enum ContractState {
  Initial = 1,
  Offered,
  Accepted,
  Rejected,
  Signed,
  Broadcast,
  Confirmed,
  Mature,
  UnilateralClosed,
  UnilateralClosedByOther,
  MutualCloseProposed,
  MutualClosed,
  Refunded,
}
