server:
  address: '0.0.0.0:8080'
oracle:
  keyFile: /key/key.pem
  keyPass:
    file: /key/pass.txt
log:
  dir: _log
  output_stdout: true
  basename: unittest.log.%Y-%m-%d
  rotation_interval: PT24H
  rotation_counts: 7
  format: json
  level: info
database:
  log: false
  port: 5432
  dbuser: postgres
  dbname: db
api:
  assets:
    btcusd:
      startDate: 2020-01-01T00:00:00Z
      frequency: PT1M
      range: P10DT
      unit: usd/btc
      precision: 0
      signconfig:
        base: 2
        nbDigits: 20
    btcjpy:
      startDate: 2020-01-01T00:00:00Z
      frequency: PT1M
      range: P2MT
      unit: jpy/btc
      precision: 0
      signconfig:
        base: 2
        nbDigits: 20
datafeed:
  cryptoCompare:
    baseUrl: https://min-api.cryptocompare.com/data
    # use apiKey and remove dummy when using with cryptocompare
  dummy:
    returnValue: 9000
